<a href="https://colab.research.google.com/github/R-ohit-B-isht/MachineLearning-CourseWork/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as py
import numpy as np

**Q1**

In [ ]:
from sklearn import datasets
from sklearn.preprocessing import MinMaxScaler
iris = datasets.load_iris() 
df = pd.DataFrame(iris.data)
df['target'] = iris.target

In [ ]:
df.head()

0    1    2    3  target
0  5.1  3.5  1.4  0.2       0
1  4.9  3.0  1.4  0.2       0
2  4.7  3.2  1.3  0.2       0
3  4.6  3.1  1.5  0.2       0
4  5.0  3.6  1.4  0.2       0

In [ ]:
from sklearn.model_selection import train_test_split
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)

trainer = MinMaxScaler()
trainer = trainer.fit_transform(x_train,y_train)

tester = MinMaxScaler()
tester = tester.fit_transform(x_test,y_test)

In [ ]:
trainer.shape

(120, 4)

In [ ]:
df_train = pd.DataFrame(df)
df_train.columns=['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid','target']
df_train.head()

sepal_len  sepal_wid  petal_len  petal_wid  target
0        5.1        3.5        1.4        0.2       0
1        4.9        3.0        1.4        0.2       0
2        4.7        3.2        1.3        0.2       0
3        4.6        3.1        1.5        0.2       0
4        5.0        3.6        1.4        0.2       0

In [ ]:
df.insert(0, "ones", 1, True)
n = df.shape[0]
alpha = 0.01

In [ ]:
df1 = df.copy()
df2 = df.copy()
df3 = df.copy()

In [ ]:
def ConvertToBinary(df,ind):
  df.is_copy = False
  for i in range(0,n):
    if df.iloc[i,5] == ind:
      df.iloc[i,5]  = 1 
    elif df.iloc[i,5] != ind:
      df.iloc[i,5]  = 0
  print(df)
  return df

In [ ]:
df1=ConvertToBinary(df1,0)
df2=ConvertToBinary(df2,1)
df3=ConvertToBinary(df3,2)

     ones  sepal_len  sepal_wid  petal_len  petal_wid  target
0       1        5.1        3.5        1.4        0.2       1
1       1        4.9        3.0        1.4        0.2       1
2       1        4.7        3.2        1.3        0.2       1
3       1        4.6        3.1        1.5        0.2       1
4       1        5.0        3.6        1.4        0.2       1
..    ...        ...        ...        ...        ...     ...
145     1        6.7        3.0        5.2        2.3       0
146     1        6.3        2.5        5.0        1.9       0
147     1        6.5        3.0        5.2        2.0       0
148     1        6.2        3.4        5.4        2.3       0
149     1        5.9        3.0        5.1        1.8       0

[150 rows x 6 columns]
     ones  sepal_len  sepal_wid  petal_len  petal_wid  target
0       1        5.1        3.5        1.4        0.2       0
1       1        4.9        3.0        1.4        0.2       0
2       1        4.7        3.2        1.3    

**REAL CODE STARTS HERE**

In [ ]:
beta_count = df.shape[1]-1
beta1 = np.zeros(beta_count)
beta2 = np.zeros(beta_count)
beta3 = np.zeros(beta_count)

In [ ]:
def findBetas(df,beta):
  x = df.iloc[:,:-1]
  y = df.iloc[:,-1]
  for iteration in range(5000):
    print(iteration)
    z = np.dot(x,beta)
    for j in range(beta_count):
      t_dJ=0
      for i in range(n):
        hypo = 1/(1+np.exp(-z[i]))
        dJ = (hypo - y[i])*x.iloc[i,j]
        t_dJ+=dJ
      beta[j]-=(alpha/n)*t_dJ 
  return beta

In [ ]:
beta1 =findBetas(df1,beta1)
beta2 =findBetas(df2,beta2)
beta3 =findBetas(df3,beta3)

In [ ]:
print(beta1)
print(beta2)
print(beta3)

[ 0.28693488  0.45010713  1.53318488 -2.40404209 -1.08580724]
[ 0.4074006   0.40638772 -1.34346969  0.42800077 -0.94167673]
[-0.80469168 -1.57367763 -1.4148281   2.33322675  2.01157281]


In [ ]:
def findProb(df,beta):
  x = df.iloc[:,:-1]
  z = np.dot(x,beta)
  fx = 1/(1+np.exp(-z))
  for i in range(n):
    if fx[i]<0.5:
      fx[i]=0
  return fx

In [ ]:
p1=findProb(df1,beta1)
p2=findProb(df2,beta2)
p3=findProb(df3,beta3)

In [ ]:
p2[0]

0.0

In [ ]:
p1[3]

0.9639827781628152

In [ ]:
y_predict = np.zeros(n)
for i in range(n):
  if p1[i]>=p2[i] and p1[i]>=p3[i]:
    y_predict[i] = 0
  elif (p2[i]>=p3[i] and p2[i]>=p1[i]):
    y_predict[i] = 1
  else:
    y_predict[i] = 2

In [ ]:
def findAccuracy(x,y):
  count = 0
  for i in range(n):
    if(x[i]==y[i]):
      count+=1
  accuracy = (count/n)*100
  print(accuracy)

In [ ]:
findAccuracy(y,y_predict)

76.0


**Q2**

**Q2(i)** 


In [ ]:
exam = pd.read_csv('exam6.txt',header = None)
exam.head(2)

0        1  2
0  0.051267  0.69956  1
1 -0.092742  0.68494  1

In [ ]:
exam.head(2)

0        1  2
0  0.051267  0.69956  1
1 -0.092742  0.68494  1

In [ ]:
exam.drop(['x1_2'],axis=1,inplace = True)
exam

0         1  2
0    0.051267  0.699560  1
1   -0.092742  0.684940  1
2   -0.213710  0.692250  1
3   -0.375000  0.502190  1
4   -0.513250  0.465640  1
..        ...       ... ..
113 -0.720620  0.538740  0
114 -0.593890  0.494880  0
115 -0.484450  0.999270  0
116 -0.006336  0.999270  0
117  0.632650 -0.030612  0

[118 rows x 3 columns]

In [ ]:
# exam.drop(['x1_3','x11_3','x111_3'],axis = 1,inplace = True)
exam

ones         0         1      x1_2      x2_2      x2_3  2
0       1  0.051267  0.699560  0.002628  0.489384  0.342354  1
1       1 -0.092742  0.684940  0.008601  0.469143  0.321335  1
2       1 -0.213710  0.692250  0.045672  0.479210  0.331733  1
3       1 -0.375000  0.502190  0.140625  0.252195  0.126650  1
4       1 -0.513250  0.465640  0.263426  0.216821  0.100960  1
..    ...       ...       ...       ...       ...       ... ..
113     1 -0.720620  0.538740  0.519293  0.290241  0.156364  0
114     1 -0.593890  0.494880  0.352705  0.244906  0.121199  0
115     1 -0.484450  0.999270  0.234692  0.998541  0.997812  0
116     1 -0.006336  0.999270  0.000040  0.998541  0.997812  0
117     1  0.632650 -0.030612  0.400246  0.000937 -0.000029  0

[118 rows x 7 columns]

In [ ]:
exam.insert(exam.shape[1]-1,"x1_2",exam[0]**2)
exam.insert(exam.shape[1]-1,"x2_2",exam[1]**2)
exam.insert(exam.shape[1]-1,"x2_3",exam[1]**3)
exam.insert(exam.shape[1]-1,"x1_3",exam[0]**3)
exam.insert(exam.shape[1]-1,"x1_4",exam[0]**4)
exam.insert(exam.shape[1]-1,"x2_4",exam[1]**4)
exam.insert(0,"ones",1,True)
exam

ones         0         1      x1_2      x2_2      x2_3          x1_3  \
0       1  0.051267  0.699560  0.002628  0.489384  0.342354  1.347453e-04   
1       1 -0.092742  0.684940  0.008601  0.469143  0.321335 -7.976812e-04   
2       1 -0.213710  0.692250  0.045672  0.479210  0.331733 -9.760555e-03   
3       1 -0.375000  0.502190  0.140625  0.252195  0.126650 -5.273438e-02   
4       1 -0.513250  0.465640  0.263426  0.216821  0.100960 -1.352032e-01   
..    ...       ...       ...       ...       ...       ...           ...   
113     1 -0.720620  0.538740  0.519293  0.290241  0.156364 -3.742131e-01   
114     1 -0.593890  0.494880  0.352705  0.244906  0.121199 -2.094682e-01   
115     1 -0.484450  0.999270  0.234692  0.998541  0.997812 -1.136964e-01   
116     1 -0.006336  0.999270  0.000040  0.998541  0.997812 -2.544062e-07   
117     1  0.632650 -0.030612  0.400246  0.000937 -0.000029  2.532156e-01   

             x1_4          x2_4  2  
0    6.907989e-06  2.394969e-01  1  
1    7.397855e-05  2.200950e-01  1  
2    2.085928e-03  2.296423e-01  1  
3    1.977539e-02  6.360222e-02  1  
4    6.939303e-02  4.701118e-02  1  
..            ...           ... ..  
113  2.696654e-01  8.423971e-02  0  
114  1.244011e-01  5.997905e-02  0  
115  5.508024e-02  9.970832e-01  0  
116  1.612020e-09  9.970832e-01  0  
117  1.601969e-01  8.781462e-07  0  

[118 rows x 10 columns]

In [ ]:
n = exam.shape[0]
alpha = 10
beta_count = exam.shape[1]
beta = np.zeros(beta_count-1)

In [ ]:
def findBetas(df,beta):
  x = df.iloc[:,:-1]
  y = df.iloc[:,-1]
  for iteration in range(1000):
    print(iteration)
    z = np.dot(x,beta)
    for j in range(beta_count-1):
      t_dJ=0
      for i in range(n):
        hypo = 1/(1+np.exp(-z[i]))
        dJ = (hypo - y[i])*x.iloc[i,j]
        t_dJ+=dJ
      beta[j]-=(alpha/n)*t_dJ 
  return beta

In [ ]:
beta = findBetas(exam,beta)

In [ ]:
beta

array([ 3.12240582,  0.50691247,  3.08012648, -3.43596764, -5.58370252,
       -2.4152913 ,  2.72967317, -9.11691845, -1.16760715])

In [ ]:
def findProb(df,beta):
  x = df.iloc[:,:-1]
  z = np.dot(x,beta)
  fx = 1/(1+np.exp(-z))
  for i in range(n):
    if fx[i]<0.5:
      fx[i]=0
    else: fx[i]=1
  return fx

In [ ]:
p = findProb(exam,beta)
p

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [ ]:
exam.iloc[:,-1]

0      1
1      1
2      1
3      1
4      1
      ..
113    0
114    0
115    0
116    0
117    0
Name: 2, Length: 118, dtype: int64

In [ ]:
def findAccuracy(x,y):
  count = 0
  for i in range(n):
    if(x[i]==y[i]):
      count+=1
  accuracy = (count/n)*100
  print(accuracy)

In [ ]:
findAccuracy(exam.iloc[:,-1],p)

80.50847457627118


**Q2(ii)**

In [ ]:
exam

ones         0         1      x1_2      x2_2      x2_3          x1_3  \
0       1  0.051267  0.699560  0.002628  0.489384  0.342354  1.347453e-04   
1       1 -0.092742  0.684940  0.008601  0.469143  0.321335 -7.976812e-04   
2       1 -0.213710  0.692250  0.045672  0.479210  0.331733 -9.760555e-03   
3       1 -0.375000  0.502190  0.140625  0.252195  0.126650 -5.273438e-02   
4       1 -0.513250  0.465640  0.263426  0.216821  0.100960 -1.352032e-01   
..    ...       ...       ...       ...       ...       ...           ...   
113     1 -0.720620  0.538740  0.519293  0.290241  0.156364 -3.742131e-01   
114     1 -0.593890  0.494880  0.352705  0.244906  0.121199 -2.094682e-01   
115     1 -0.484450  0.999270  0.234692  0.998541  0.997812 -1.136964e-01   
116     1 -0.006336  0.999270  0.000040  0.998541  0.997812 -2.544062e-07   
117     1  0.632650 -0.030612  0.400246  0.000937 -0.000029  2.532156e-01   

             x1_4          x2_4  2  
0    6.907989e-06  2.394969e-01  1  
1    7.397855e-05  2.200950e-01  1  
2    2.085928e-03  2.296423e-01  1  
3    1.977539e-02  6.360222e-02  1  
4    6.939303e-02  4.701118e-02  1  
..            ...           ... ..  
113  2.696654e-01  8.423971e-02  0  
114  1.244011e-01  5.997905e-02  0  
115  5.508024e-02  9.970832e-01  0  
116  1.612020e-09  9.970832e-01  0  
117  1.601969e-01  8.781462e-07  0  

[118 rows x 10 columns]

In [ ]:
n = exam.shape[0]
lam = 0.2
alpha = 10
beta_count = exam.shape[1]
beta = np.zeros(beta_count-1)

In [ ]:
def findBetas(df,beta):
  x = df.iloc[:,:-1]
  y = df.iloc[:,-1]
  for iteration in range(1000):
    print(iteration)
    z = np.dot(x,beta)
    for j in range(beta_count-1):
      t_dJ=0
      for i in range(n):
        hypo = 1/(1+np.exp(-z[i]))
        dJ = (hypo - y[i])*x.iloc[i,j]+(lam/n)*beta[j]
        t_dJ+=dJ
      beta[j]-=(alpha/n)*t_dJ 
  return beta

In [ ]:
beta = findBetas(exam,beta)
beta

In [ ]:
beta

array([ 2.98680855,  0.83247894,  2.15600326, -3.93892338, -2.83407251,
       -0.89673653,  0.34134519, -3.35978371, -2.69929316])

In [ ]:
p = findProb(exam,beta)
findAccuracy(exam.iloc[:,-1],p)

77.11864406779661


In [ ]:
# -*- coding: utf-8 -*-
"""ML Assignment-6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c-HgxUuGN22phxZlyRonwbOmRqesiXA2

#**Q3**
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix,plot_confusion_matrix

df=pd.read_csv('/content/gender_classification_v7.csv')

df.head()

df.info()

df['gender'].value_counts()

df['Gender']=df['gender'].map({'Male':1,'Female':0})

df=df.drop('gender', axis = 1)
df.head()

x = df.iloc[:,0:7]
y = df.iloc[:,7]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=100)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, plot_confusion_matrix

knn = KNeighborsClassifier()
from sklearn.model_selection import GridSearchCV
k_range = list(range(1, 31))
param_grid = dict(n_neighbors=k_range)
  
# defining parameter range
grid = GridSearchCV(knn, param_grid, cv=10, scoring='accuracy', return_train_score=False,verbose=1)
  
# fitting the model for grid search
grid_search=grid.fit(x_train, y_train)

print(grid_search.best_params_)

accuracy = grid_search.best_score_ *100
print("Accuracy of training with tuning is : {:.2f}%".format(accuracy) )

knn = KNeighborsClassifier(n_neighbors=19)

knn.fit(x, y)

y_test_hat=knn.predict(x_test) 
print(y_test_hat)

test_accuracy=accuracy_score(y_test,y_test_hat)*100

print("Accuracy of testing dataset with tuning is : {:.2f}%".format(test_accuracy) )

"""#**Q1**"""

from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

column = ['label','text']
df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv', sep = '\t', names = column)

df.head()

df.info()

X = df['text']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=13,
                                                    shuffle=True , stratify=y)
print(y.value_counts())

"""The multinomial Naive Bayes classifier is used to classify discrete features like word counts.
Here we use CountVectorizer to turn the collection of text SMS into numerical features. Default values are kept as they give good results.
"""

pipe = Pipeline(steps=[('vectorize', CountVectorizer(ngram_range=(1, 1), token_pattern=r'\b\w+\b')),
                       ('classifier', MultinomialNB())])

pipe.fit(X_train, y_train)

y_predict = pipe.predict(X_test)

print(accuracy_score(y_test, y_predict))
print(classification_report(y_test, y_predict))

mat = confusion_matrix(y_test, y_predict)
sns.heatmap(mat, square=True, annot=True, fmt='d', cbar=True, cmap='coolwarm', linewidths=5)
plt.xlabel('predicted value')
plt.ylabel('true value')
plt.show()

SMS = [["You just won 50000 dollars worth cash prizes"],
       ["You can redeem 5000 dollars in cash"],
       ["I'll come within 5 minutes to meet you"],
       ["You just won 50 dollars to play games"],
       ["How are you doing my friend?"],
       ["You just won 50 dollars to have sex"],
       ["Greg, can you call me back once you get this?"],
       ["You just won 50 dollars to buy food"],
       ["Winner! To claim your gift call 0908878877"],
       ["Attend this free COVID webinar today: Book your session now"],
       ["Your online account has been locked. Please verify payment information"]]

for sms in SMS:
  print(pipe.predict(sms), sms)

"""#**Q2**"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import matplotlib.colors as colors
import seaborn as sns
import itertools
from scipy.stats import norm
import scipy.stats
from sklearn.naive_bayes import GaussianNB

# %matplotlib inline
sns.set()

#Load the data set
iris = sns.load_dataset("iris")
iris = iris.rename(index = str, columns = {'sepal_length':'1_sepal_length','sepal_width':'2_sepal_width', 'petal_length':'3_petal_length', 'petal_width':'4_petal_width'})

#Plot the scatter of sepal length vs sepal width
sns.FacetGrid(iris, hue="species", size=7) .map(plt.scatter,"1_sepal_length", "2_sepal_width", )  .add_legend()
plt.title('Scatter plot')
df1 = iris[["1_sepal_length", "2_sepal_width",'species']]

"""(i)"""

def predict_NB_gaussian_class(X,mu_list,std_list,pi_list): 
    #Returns the class for which the Gaussian Naive Bayes objective function has greatest value
    scores_list = []
    classes = len(mu_list)
    
    for p in range(classes):
        score = (norm.pdf(x = X[0], loc = mu_list[p][0][0], scale = std_list[p][0][0] )  
                * norm.pdf(x = X[1], loc = mu_list[p][0][1], scale = std_list[p][0][1] ) 
                * pi_list[p])
        scores_list.append(score)
             
    return np.argmax(scores_list)

def predict_Bayes_class(X,mu_list,sigma_list): 
    #Returns the predicted class from an optimal bayes classifier - distributions must be known
    scores_list = []
    classes = len(mu_list)
    
    for p in range(classes):
        score = scipy.stats.multivariate_normal.pdf(X, mean=mu_list[p], cov=sigma_list[p])
        scores_list.append(score)
             
    return np.argmax(scores_list)

# Plotting decision boundaries
#Estimating the parameters
mu_list = np.split(df1.groupby('species').mean().values,[1,2])
std_list = np.split(df1.groupby('species').std().values,[1,2], axis = 0)
pi_list = df1.iloc[:,2].value_counts().values / len(df1)

# Our 2-dimensional distribution will be over variables X and Y
N = 100
X = np.linspace(4, 8, N)
Y = np.linspace(1.5, 5, N)
X, Y = np.meshgrid(X, Y)

#fig = plt.figure(figsize = (10,10))
#ax = fig.gca()
color_list = ['Blues','Greens','Reds']
my_norm = colors.Normalize(vmin=-1.,vmax=1.)

g = sns.FacetGrid(iris, hue="species", size=10, palette = 'colorblind') .map(plt.scatter, "1_sepal_length", "2_sepal_width",)  .add_legend()
my_ax = g.ax


#Computing the predicted class function for each value on the grid
zz = np.array(  [predict_NB_gaussian_class( np.array([xx,yy]).reshape(-1,1), mu_list, std_list, pi_list) 
                     for xx, yy in zip(np.ravel(X), np.ravel(Y)) ] )


#Reshaping the predicted class into the meshgrid shape
Z = zz.reshape(X.shape)


#Plot the filled and boundary contours
my_ax.contourf( X, Y, Z, 2, alpha = .1, colors = ('blue','green','red'))
my_ax.contour( X, Y, Z, 2, alpha = 1, colors = ('blue','green','red'))

# Addd axis and title
my_ax.set_xlabel('Sepal length')
my_ax.set_ylabel('Sepal width')
my_ax.set_title('Gaussian Naive Bayes decision boundaries')

plt.show()

"""(ii)"""

from sklearn.naive_bayes import GaussianNB

#Setup X and y data
X_data = df1.iloc[:,0:2]
y_labels = df1.iloc[:,2].replace({'setosa':0,'versicolor':1,'virginica':2}).copy()

#Fit model
model_sk = GaussianNB(priors = None)
model_sk.fit(X_data,y_labels)


# Our 2-dimensional classifier will be over variables X and Y
N = 100
X = np.linspace(4, 8, N)
Y = np.linspace(1.5, 5, N)
X, Y = np.meshgrid(X, Y)

#fig = plt.figure(figsize = (10,10))
#ax = fig.gca()
color_list = ['Blues','Greens','Reds']
my_norm = colors.Normalize(vmin=-1.,vmax=1.)

g = sns.FacetGrid(iris, hue="species", size=10, palette = 'colorblind') .map(plt.scatter, "1_sepal_length", "2_sepal_width",)  .add_legend()
my_ax = g.ax


#Computing the predicted class function for each value on the grid
zz = np.array(  [model_sk.predict( [[xx,yy]])[0] for xx, yy in zip(np.ravel(X), np.ravel(Y)) ] )


#Reshaping the predicted class into the meshgrid shape
Z = zz.reshape(X.shape)


#Plot the filled and boundary contours
my_ax.contourf( X, Y, Z, 2, alpha = .1, colors = ('blue','green','red'))
my_ax.contour( X, Y, Z, 2, alpha = 1, colors = ('blue','green','red'))

# Addd axis and title
my_ax.set_xlabel('Sepal length')
my_ax.set_ylabel('Sepal width')
my_ax.set_title('Gaussian Naive Bayes decision boundaries')

plt.show()

"""Accuracy for both the implementations"""

#Numpy accuracy
y_pred = np.array(  [predict_NB_gaussian_class( np.array([xx,yy]).reshape(-1,1), mu_list, std_list, pi_list) 
                     for xx, yy in zip(np.ravel(X_data.values[:,0]), np.ravel(X_data.values[:,1])) ] )
display(np.mean(y_pred == y_labels))

#Sklearn accuracy
display(model_sk.score(X_data,y_labels))