<a href="https://colab.research.google.com/github/R-ohit-B-isht/MachineLearning-CourseWork/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
a=np.array([[1,2],[2,3]])

In [ ]:
array=np.array([1,2,3,4,5])
array=array[::-1]
array

array([5, 4, 3, 2, 1])

In [ ]:
array1=np.array([[1,2,3],[2,3,4],[3,4,5]])
#array1=array1.flatten()
#array1=array1.ravel()
array1=array1.reshape([1,9])
array1

array([[1, 2, 3, 2, 3, 4, 3, 4, 5]])

In [ ]:
arr1=np.array([[1,2],[2,3]])
arr2=np.array([[1,2],[2,3]])
print(arr1==arr2)

[[ True  True]
 [ True  True]]


In [15]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
def maxer(x):
  val,count=np.unique(x,return_counts=True)
  max_index=np.argmax(count, axis=0)
  maxct=max(count)
  myVal=val[max_index]
  myVal
  print(maxct," ", myVal)
  indexes=np.where(x==myVal)
  print(indexes )

maxer(x)
maxer(y)

5   1
(array([0, 5, 7, 8, 9]),)
3   1
(array([0, 1, 2]),)


In [23]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
gfg
total = gfg.sum()
total_rows=gfg.sum(axis=1)
total_cols=gfg.sum(axis=0)
print(total,total_rows,total_cols,sep="\n")

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [30]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
trace = np.trace(n_array)
ei,ex=np.linalg.eig(n_array)
inver=np.linalg.inv(n_array)
deter=np.linalg.det(n_array)
print(trace,ei,ex,inver,deter,sep="\n \n")


176
 
[98.16835147 28.097044   49.73460452]
 
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
 
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
 
137180.0000000001


In [36]:
def fds(m1,m2):
  result=np.dot(m1,m2)
  cover=np.cov(m1,m2)
  print(result,cover,sep="\n \n")

# p = [[1, 2], [2, 3]]
# q = [[4, 5], [6, 7]]
# fds(p,q)
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
fds(p,q)

ValueError: ignored